server:
  port: 3344
spring:
  application:
    name: spring-cloud-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liurq123/springcloud-config.git
          search-paths:
            - springcloud-config
        label: main     #  git上的分支

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

