server:
  port: 3344
spring:
  application:
    name: spring-cloud-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liurq123/springcloud-config.git
          search-paths:
            - springcloud-config
        label: main     #  git上的分支
# 消息总线端rabbitmq配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
# 暴露bus-refresh刷新配置端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

