server:
  port: 9527

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 注册中心动态 创建路由
      routes:
        - id: payment_route1
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=/payment/**
        - id: payment_routh2  # 路由ID ， 没有固定的规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-SERVICE
          predicates:
            - Path=/payment/serviceport  # 断言，路径相匹配的进行路由
            - Cookie=chocolate, ch.p
            - Before=2021-06-20T21:50:21.031+08:00[Asia/Shanghai]   # 此请求此路由需要配置的此时间之前

#            - After=2021-06-20T21:20:21.031+08:00[Asia/Shanghai]   # 此请求此路由需要配置的此时间之后

#          - Header=X-Request-Id, \d+

#        - Header=X-Request-Id, \d+

